data_source: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts:
  artifacts_directory: artifacts
  raw_local_directory: raw_local_dir
  raw_local_file: data.csv

  split_data_dir: split_data
  train: train.csv
  test: test.csv
